### ISSUE TITLE
Breaks when trying to move to a nonexistent space

### ISSUE THREAD

**Issue by a-morales** [koekeishiya/kwm#131]
When there are 2 or more space in a workspace, and you try to go a non-existent space beyond the current space (try to go left on the leftmost space) then KWM looses the screen and can't focus on windows. KWM works again when moving to an existing space 

I'm guessing this is a minor bug when doing the checks for a transition.

**Comment by koekeishiya** [comment]
This behaviour is happening due to changes done here:
https://github.com/koekeishiya/kwm/commit/e1568321ddf69cb58be65c6e899324fb2ba921b2

Kwm doesn't really "break", but it expected a space-transition to happen, and thus is waiting for one.
I find this behaviour really annoying as well, but the issue that was fixed by this was way worse.
I'll look into this more for sure.

**Comment by a-morales** [comment]
Ok, yeah this seems like a minor annoyance compared to the previous issue. If I have time over the weekend I can work on this and some other bugs listed

**Comment by a-morales** [comment]
This issue is still present in the current release if you go to the non-existent space and don't move the mouse, then KWM doesn't regain focus of the current screen

**Comment by koekeishiya** [comment]
> This issue is still present in the current release if you go to the non-existent space and don't move the mouse, then KWM doesn't regain focus of the current screen

Working as intended for now, will see if this gets changed in the future.

**Comment by koekeishiya** [comment]
This is once again an issue, after rewriting the space-transition code to rely on `NSWorkspaceActiveWorkspaceDidChangeNotification`

**Comment by matthewdias** [comment]
Is this still an issue? I haven't come across it. What are the steps to reproduce?

**Comment by koekeishiya** [comment]
This is still an issue, yeah. No idea how to fix it without reintroducing #122

**Comment by dominiklohmann** [comment]
I'm pretty sure this is related: kwm also breaks when starting a space transition and then cancelling it. It stops working again as soon as you close a window on the space.

**Comment by koekeishiya** [comment]
> I'm pretty sure this is related: kwm also breaks when starting a space transition and then cancelling it

Correct. This is the exact same reason as the above issue.

**Comment by koekeishiya** [comment]
Fixed in latest commit.
