### ISSUE TITLE
Rewrite code for multiple-monitor support

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#161]
Felt like having a single issue to track this progress. I'll keep updating here regarding the current status of this.

So in commit 23c77d4ee0f8cfa2e0b9f564816ca40ce8bdb2aa I have been able to have the active space identifier update properly upon a screen transition. This should allow for actually being able to use multiple monitors properly without the annoyance of having the window-trees reset all the time.

In an earlier commit (812e64af2313259d92c52d4f0c0c4f7e2975d9e3) the space-transition code was rewritten to use the NSWorkspaceDidActiveSpaceChange notification.

The issues remaining I would think are having Kwm properly handle disconnection of monitors, awake from sleep and similar. See #123, #127

**Comment by alexfedoseev** [comment]
Even without second display connected window-trees reset quite often on focus on window-tree's space. Not on every unfocus/focus, but often. I'm not sure what's causing this though, it happens kinda randomly.

**Comment by koekeishiya** [comment]
It should be stable in the latest commit. During the re-write there were a lot of things I didn't think of at first, that were done at a later time.

**Comment by chrishoage** [comment]
I have a suspicion that the current best solution for #123, #127, and #108 is to not react to display changes until a timeout has expired, and keep resetting that timeout every time a display change is noticed. 

After the timeout has expired then kwm reads the display state and adjusts accordingly. 

Unless there is some API to help you, I'm not sure how else the "fake" displays can be solved. As they appear to be "real" displays that get removed. They are only there for a short time during the transition. 

Switching the iGPU, waking from sleep with a 4k external monitor, and changing displays should be covered by that approach?

**Comment by koekeishiya** [comment]
I'll probably have to give something like that a try. I really have no idea what to do regarding these, as there are indeed on APIs available (that I have been able to find at the very least).

**Comment by alexfedoseev** [comment]
Looks like refresh issue is fixed, but it's replaced by another: now when I refocus on some space, kwm ignores everything (it's running, but it doesn't spawn windows, ignores all keybindings, tree restore doesn't work etc), so I have to `kwmc quit` to make it responsive again.

**Comment by koekeishiya** [comment]
You sure that is not connected to #131 ?

**Comment by alexfedoseev** [comment]
> You sure that is not connected to #131 ?

I just updated kwm from master, restarted osx and tried to go to non-existent space. Kwm runs fine, so I guess it's not it. After restart I noticed that my bindings `kwmc screen -f [id]` don't work, but after a 5 minutes they were back w/o kwm restart. Now everything works fine, I'll write back here if the issue will appear again.

**Comment by alexfedoseev** [comment]
Well, here is what's happening:

* my system keybindings to switch spaces are getting broken and after some movements through the windows/screens they work again
* same happening for `kwmc screen -f [id]` bindings

Looks like it's happening when I open some very new window of some app (but not every). But it's just a guess.

**Comment by koekeishiya** [comment]
I don't really see how that would be connected to earlier changes tho. Could you try and revert back to Kwm Version 1.1.1 and see if these issues still happen?

**Comment by alexfedoseev** [comment]
Sure, will do a bit later today :+1:

**Comment by alexfedoseev** [comment]
Hah, I just switched to iTerm to revert back to prev version and kwm ignores everything again, so this issue still appears on master branch.

Should I switch to 1.1.1 and check `screen -f` there?

**Comment by koekeishiya** [comment]
Make sure that "Secure keyboard entry" is not enabled for iTerm.
If that does not fix it, try re-enabling accessibility access for Kwm.

**Comment by alexfedoseev** [comment]
> Make sure that "Secure keyboard entry" is not enabled for iTerm.
It's disabled.

> If that does not fix it, try re-enabling accessibility access for Kwm.
I did it right after kwm update -> osx restart.

**Comment by alexfedoseev** [comment]
BTW it's not only iTerm related, all spaces / windows ignored, as well as all of the keybindings.

**Comment by koekeishiya** [comment]
> It's disabled.
> I did it right after kwm update -> osx restart.

Not sure what would be causing it then. Everything works fine for me (better than it used to).

**Comment by chrishoage** [comment]
A new issue I have discovered in the last day: Sometimes `kwmc screen -f` does not seem to actually give focus to the other screen. Kwm _thinks_ it did because `kwmc read tag` updates appropriately, but no commands work until `screen -f` is used to "bring" focus back to the previous screen.

**Comment by matthewdias** [comment]
not sure if this is related, or it's already been discussed, but the top half of my screen flickers when switching gpus.

**Comment by koekeishiya** [comment]
> A new issue I have discovered in the last day: Sometimes kwmc screen -f does not seem to actually give focus to the other screen. Kwm thinks it did because kwmc read tag updates appropriately, but no commands work until screen -f is used to "bring" focus back to the previous screen. 

I know this happens when the screen that is supposed to get focus,  has no windows on it. (which is a bug). Have not come across it in other situations tho.

**Comment by koekeishiya** [comment]
> A new issue I have discovered in the last day: Sometimes kwmc screen -f does not seem to actually give focus to the other screen. Kwm thinks it did because kwmc read tag updates appropriately, but no commands work until screen -f is used to "bring" focus back to the previous screen. 

Issue with switching between GPUs have been mentioned, but it is not something I can work on as I do not have a macbook with a dGPU.

**Comment by chrishoage** [comment]
> Have not come across it in other situations tho.

This didn't start until very recently, and has the same behavior as if a display has no windows on it. It was in monocle if it makes any difference? 

In any case it's not super common, and using the mouse fixes it. So it seems keyboard-centric?

**Comment by koekeishiya** [comment]
Pretty sure it broke in  this commit: 86c453af72b7d75311413adff499e1a04fd919b0

The exact line of code that was removed, that could impact this: 
```
CGWarpMouseCursorPosition(CGPointMake(FocusFirstNode->Container.X + FocusFirstNode->Container.Width / 2,
```

Which was only handled upon using keyboard to give focus.

**Comment by chrishoage** [comment]
That does indeed sound pretty likely

**Comment by koekeishiya** [comment]
I have very limited time to spend on Kwm these days, and will not be able to have any real progress on this issue before summer, at the very least.

The logic that needs to be revisited, is how Kwm handles the following scenarios:
 - (dis)connection of display
 - enter / leave sleep
 - enter / leave clamshell mode
 - switching active GPU
 - (dis)connection of display while already in clamshell mode
 
At this moment, I have no idea how to respond if the Main/Primary display is changed as a result of the actions listed above.

The core of the changes for the above behaviour as far as I know at the moment, would have to be in "DisplayReconfigurationCallback()" function @ kwm/display.cpp 

If anyone is interested in taking a look at this, that would be very much appreciated.
The following are links to some apple dev documentation that could be useful:
 - [Quartz Display API](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/Quartz_Services_Ref/)
 - [Display Notifications](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Conceptual/QuartzDisplayServicesConceptual/Articles/Notification.html)

**Comment by chrishoage** [comment]
> Any (detailed) insight into how OSX behaves during these actions could also be helpful for solving these issues when I finally do get time to take a proper look at this.

Are there things in particular you are looking for / would be of great use? I'm very willing to collect any information you need about the behavior. I have a setup that checks all the problem boxes: 4k monitor, discrete graphics card, etc... 

Let me know what data would be useful and I'll collect it.

**Comment by koekeishiya** [comment]
> Are there things in particular you are looking for / would be of great use?

Uh, more or less the messages that OSX reports to the `DisplayReconfigurationCallback()` when it performs any of the actions listed above, or when only a single monitor enters or awakes from sleep.
Basically, any information that lets us tell the difference between which action actually happened is valuable.

**Comment by chrishoage** [comment]
Are the debug logs in place that would provide that information? I can spend some time in debug mode adding and removing a display, switching the graphics card, sleeping and waking. Then supply the logs associated with the actions for later examination?

**Comment by koekeishiya** [comment]
There are logs for when a display is  detected, removed, and enters sleep I believe.

**Comment by chrishoage** [comment]
> Some other flags that is probably worth tracking, which Kwm does not atm.

Throw in any logs that might help you track down odd behavior and I will collect data later this week / this weekend.

**Comment by koekeishiya** [comment]
> Throw in any logs that might help you track down odd behavior and I will collect data later this week / this weekend. 

Will get to this when I have time, hopefully before this weekend.

**Comment by chrishoage** [comment]
> Will get to this when I have time, hopefully before this weekend.

Ping me when you do, and I'll start the testing.

**Comment by koekeishiya** [comment]
Is this issue resolved with the latest patch from @cHoco ?

**Comment by jhenahan** [comment]
Resolved for me!

**Comment by koekeishiya** [comment]
I'm gonna close this for now. Feel free to open new issues if necessary.
