### ISSUE TITLE
Bug: Switching spaces behaviour just with some apps focused

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#217]
I noticed that the strange - and annoying - behaviour, consisting in the space recently switched being pulled off, returning to the previous space, is just happening when some apps are focused on the former space.
In this regard, I saw that if i switch to another space when my focused window is Finder, there's no problem at all: the new space is switched and it stays in its place. If I switch when an iTerm window is focused, the space do not stick and it will be pushed by the previous space which as an iTerm window on it. So, if go from space 3 to space 5, and if there's no iTerm windows in space 4, the screen suddenly and instantly return to space 3. 
The same did not happen if I use Terminal.app...

So, maybe there's something wrong with the focus behaviour in iTerm. Any clues?

**Comment by AhmedAA** [comment]
I have the same issue. Not related to iTerm.
Did not know however that you just need Finder focused instead. At least that's a workaround for now.

I first got it in the recent release through Brew.

**Comment by koekeishiya** [comment]
> I first got it in the recent release through Brew.

I believe this has been fixed @ master. I am unable to reproduce at least.

**Comment by andreaspada** [comment]
Unfortunately not. I compiled the master branch yesterday, before writing this "bug issue". Is something that is happening for a while, just yesterday I noticed that was possibly related to iTerm, which seem not is the case. I explain... I just quitted iTerm. So, this is no more in the game.

Space1: empty
Space2: numbers - fullscreen
Space3: finder - tiling
Space4: empty
Space5: safari
Space6: safari

If I switch with ctrl+1 to Space1, go to space 1 than immediately to Space3. If I go to Space4, it switch to Space3. Than... 

--- !!!

I was writing and checking that I'm writing right, when I discovered that my spaces are changing position! Whenever the automatic switch happens, some space switch with another... !!! Maybe an OSX 10.11.3 bug??? So, Space2 became Space3... and the same again, and a again...

**Comment by koekeishiya** [comment]
> I was writing and checking that I'm writing right, when I discovered that my spaces are changing position! Whenever the automatic switch happens, some space switch with another... !!! Maybe an OSX 10.11.3 bug??? So, Space2 became Space3... and the same again, and a again...

This is a feature in OSX. System Preferences -> Mission Control -> Automatically rearrange Spaces based on most recent use

**Comment by andreaspada** [comment]
Wow! I'm so stupid! Did not noticed that...

**Comment by AhmedAA** [comment]
> This is a feature in OSX. System Preferences -> Mission Control -> Automatically rearrange Spaces based on most recent use

I did not have this activated, still have the issue.
Will have to research it further, don't have anything more specific to report right now.

**Comment by AhmedAA** [comment]
Seems that restarting/logging in or out fixed it.

**Comment by koekeishiya** [comment]
> Anyway, the problem is basically as @andreaspada already explained.
I go from a space with windows, to an empty space (either with touchpad gesture, or hotkey) and it instantly travels back to the space I came from with windows. I haven't changed anything since moving from the previous release to this.
As I stated earlier, I am running through Brew, if it has been fixed on master, then I will just wait until a new release comes :) It is not critical.

Same as #204 - Fixed @ master
