### ISSUE TITLE
`Connection Failed!` Error and No Information about Fixing

### ISSUE THREAD

**Issue by aakashjog** [koekeishiya/kwm#269]
The error `Connection Failed!` shows up whenever any `kwmc` command except for `kwmc help` is used.
It also shows up in the upper-left corner of the nerdbar widget for Übersicht.

There is no information included in the README or anywhere else about fixing this error.

The problem is particularly worse in v1.1.5 and doesn't get solved automatically as it did in v1.1.4 and older.

**Comment by koekeishiya** [comment]
`Connection Failed` is the message showns when `kwmc` is unable to connect to the local server `kwm` runs on 3020. The only thing that makes sense is that your Kwm seems to crash for some reason.

**Comment by aakashjog** [comment]
Okay, so did the update break my `kwm`? If so, how can I fix it?

I am running OS X 10.11.4 on an 11" MacBook Air.

**Comment by koekeishiya** [comment]
The syntax of some `kwmc` commands changed. Just compare your .kwmrc file to the one provided with homebrew, and update ones that got changed.

**Comment by aakashjog** [comment]
I'm using the default `.kwmrc` which came with v1.1.5.

**Comment by koekeishiya** [comment]
Just to make sure, you placed the default .kwmrc at `$HOME/.kwm/kwmrc` yeah?
Also, you might need to upgrade to the latest xcode, or disable the borders.

**Comment by MatanSilver** [comment]
I've had this problem and it was fixed by updating xcode, if that helps

**Comment by aakashjog** [comment]
My Xcode is v7.3, the latest one. That shouldn't be the issue.

**Comment by koekeishiya** [comment]
Any update on this? I'm 99% certain this is caused by a faulty kwmrc file.

**Comment by aakashjog** [comment]
I still get the error, but with less frequency. I think that the issue has to do with my system.

**Comment by koekeishiya** [comment]
Do you still have issues running version 2.0.1 ?
Keep in mind, you have to update your $Home/.kwm/kwmrc due to syntax changes.

**Comment by aakashjog** [comment]
There are no issues with v2.0.1. :+1:

Also, the latest version on homebrew is v1.1.5. I don't know if that's intentional, but just wanted to point that out. I had to install v2.0.1 from the source.

**Comment by codedmart** [comment]
I am not sure what I am doing wrong? I have installed kwm just now from homebrew. First time installing it. I followed the instructions after install:
```
homebrew/binary/kwm: stable 2.0.3
Tiling window manager with focus follows mouse for OSX.
https://koekeishiya.github.io/kwm/
/usr/local/Cellar/kwm/2.0.3 (6 files, 5.4M) *
  Built from source
From: https://github.com/Homebrew/homebrew-binary/blob/master/kwm.rb
==> Caveats
Copy the example config from /usr/local/Cellar/kwm/2.0.3/kwmrc into your home directory.
  mkdir -p ~/.kwm
  cp /usr/local/Cellar/kwm/2.0.3/kwmrc ~/.kwm/kwmrc

To have launchd start homebrew/binary/kwm at startup:
  sudo cp -fv /usr/local/opt/kwm/*.plist /Library/LaunchDaemons
  sudo chown root /Library/LaunchDaemons/homebrew.mxcl.kwm.plist
Then to load homebrew/binary/kwm now:
  sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.kwm.plist
```
Nothing happens, and if I try `kwmc start` or `kwmc config launchd enable` I get `Connection failed!`. I can start kwm manually `/usr/local/opt/kwm/kwm` but when I try to use `cmd-return` to launch iTerm I get this error `FSPathMakeRef(/Applications/iTerm2.app) failed with error -43.`

Thanks

**Comment by koekeishiya** [comment]
The homebrew instructions are wrong and should not be used. Undo the changes homebrew told you to do:
```
sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.kwm.plist
sudo rm /Library/LaunchDaemons/homebrew.mxcl.kwm.plist
```
and do the following instead:
```
cp /usr/local/opt/kwm/*.plist ~/Library/LaunchAgents`
launchctl load -w ~/Library/launchAgents/homebrew.mxcl.kwm.plist`
```

**Comment by codedmart** [comment]
@koekeishiya Awesome thanks! Now it is starting on it's own. `cmd-return` does not open a iTerm though? Also how did you remove you titlebars in the screenshot?

**Comment by koekeishiya** [comment]
> Awesome thanks! Now it is starting on it's own. cmd-return does not open a iTerm though? Also how did you remove you titlebars in the screenshot?

Make sure you have iTerm2 and not just iTerm, by default `cmd-return` will try to run `open -na /Applications/iTerm2.app`
For information about my setup, see #2
