### ISSUE TITLE
Multi-display support appears to be broken when display is empty

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#65]
When 2nd display is empty: 

At the latest commit I can not send a window to a screen, I can not use the key board to give focus to a screen, I can not change the layout of a screen. When autoraise is used to give focus to a screen the "Apple" menu item is always selected if the screen is empty. Capture doesn't work. 

Everything works fine if the space has a window, but if it is empty nothing appears to work.

(I can float a window drag it over and unfloat and everything starts working again.)

**Comment by chrishoage** [comment]
I can get the menu bar menus to open when there is something on the display: If you move the mouse over the menu bar right when you get to the display it will trigger focus on the menu bar menu.

**Comment by koekeishiya** [comment]
Not sure if this is something I can fix, or even want to spend time fixing.
There are zero API's for OSX to deal with multiple monitors, so it is a real pain to write a workaround.

Will look into it the above things at some point in time.

**Comment by chrishoage** [comment]
This behavior didn't exist before last night.

**Comment by koekeishiya** [comment]
It's side effects of having everything work properly when there is at least 1window on the screen.
All the previous focus bugs are no longer there (at least they shouldn't be).

**Comment by chrishoage** [comment]
Actually move focus to screen appears to be worse than it was before. It almost never gives focus to the other screen now, and when it does screen 0 can _never_ get focus back with out using the mouse.

**Comment by koekeishiya** [comment]
Whats your setup like? Worked perfectly for me when I tested last night.

**Comment by chrishoage** [comment]
Primary (has the menu bar in Displays -> Arraignment) is an external monitor. Secondary is my laptop monitor. Behavior persisted after a reboot along with `rm -rf ./kwm/bin` and a make install after a pull. 

To be clear using kwmc to give a screen focus _does_ sometimes work, but when all windows loose focus I can't use `window -f` to give focus when it does, and all windows losing focus _appears_ to be happening more. 

That coupled with the empty display issues make it feel like a regression (because I used to be able to send a window to an empty display before (or at least I thought). 

When I get some time later today I'll go though previous commits and see if any of them exhibit similar or better behavior.

**Comment by koekeishiya** [comment]
Can you check if the same problems occurr with the laptop monitor as primary and external as secondary?

**Comment by chrishoage** [comment]
Problems do indeed persist when the laptop monitor is the primary. Focus can get "stuck" on a monitor. Capture doesn't work when display is empty (i'm fairly sure this worked before? I could be mistaken though)

Before when moving focus to a screen and it focused no window it could be fixed the next time the screen focus was cycled, now when it gets "stuck" screen focus must be cycled many times (like 5?) before _any_ window get focus again.

**Comment by koekeishiya** [comment]
Whats your focus-follows-mouse and mouse-follows-focus etc set to?
I tested it just now and it works perfectly here.
What I did: 
Connect display,   
move cursor to display,   
spotlight->finder,   
`screen -f pref`   
open iTerm,   
`screen -m next` on the iTerm window, 
and then just `window -f next` til I get back to my main monitor.

**Comment by chrishoage** [comment]
```
kwmc config focus autoraise
kwmc config focus mouse-follows enable
```

I have not been testing kwm with disconnecting and reconnecting the display, both displays were present when kwm started.

I tried to disable mouse-follows and was still able to get "stuck" on the 2nd display after a few cycles.

**Comment by koekeishiya** [comment]
I might look at it later tonight, working on serialization atm - testing saving / reading the stored tree currently

**Comment by chrishoage** [comment]
No worries, just wanted to create the ticket to track it.

**Comment by koekeishiya** [comment]
So I noticed that you had the menu-bar visible, and I did the same to try and reproduce. I do indeed get these same problems now.
However, would you mind just turning the menu-bar to autohide and let me know if the current implementation is better than the previous one? (assuming that I can fix the problems with menu-bar being visible).

**Comment by chrishoage** [comment]
When I have the menu bar hidden and 
```
kwmc config menu-fix enable
kwmc config focus autoraise
```

set I can not get autorise to work at all. Moving window focus with `window -f prev | next` also does not function for me when I have the menu bar hidden. 

With `menu-fix disable` autoraise does work.

**Comment by chrishoage** [comment]
Ah, I have found the issue. I was using https://github.com/puffnfresh/Honer.app to place a border around the window.

I was actually curious your opinion on possibly adding a border for the focused window and a separate color for the `marked` window? 

I remember seeing you have a script for hammerspoon to make a border so I will use that instead of Honer.

**Comment by koekeishiya** [comment]
I would love to be able to create a border from within Kwm, but there is no way to do this from within C code. I have to use objective-c code to call into the cocoa framework. I could potentially create some C-wrapper functions that calls objective-c code to do this, but I have no experience with that, or objective-c in general.

Also on a related note, the `menu-fix` does not need to be enabled when using the OSX menubar, the name might be misleading. What it does, (if enabled) is when it detects any window on screen with a window-layer that is not 0 (these are overlay-windows, context menus, notifications) focus follows mouse will temporarily stop, til these goes away.

**Comment by chrishoage** [comment]
I had `menu-fix` off previously and just lived with janky menus. I have not got around to making a replacement for iStat menus and the rest of the menu. But after seeing menu-fix actually work with the menu bar hidden I will probably be more inclined to do so now. 

It looks like Honer was the source of all of the problems aside from the "Empty Display" issue, Sorry about that. 

Swift should also be able to call cocca and have a C wrapper as another option to learn.

**Comment by chrishoage** [comment]
I have figured out how to reproduce the losing focus issue with great consistency: 

Change `border:setLevel("normal")` to `border:setLevel("floating")` in your hammerspoon lua script. 

Starting on the left 1st container `window -f next`, `screen -f next`, `screen -f next` repeat until focus is lost. Takes 1 - 2 cycles to happen. 

Screen focus works pretty much flawlessly when `border:setLevel("normal")`. Unfortunately any setting below "tornOffMenu" makes overlays like Alfred and Menus appear under the border. It also messes with the window positioning when in exposé. 

http://www.hammerspoon.org/docs/hs.drawing.html#windowLevels

This is probably what the issue was with Honer, I have no idea if this is fixable, but at least you should be able to reproduce it.

**Comment by koekeishiya** [comment]
Focus between monitors is still bad and gets stuck quite often. It also sometimes re-creates the tree. I notice that the tree-recreate thing (where you have to do `kwmc tree -c refresh` happens right after the mouse is used to unstuck focus). Due to this behaviour, these two bugs seem to be connected in some way.

I really do not know how good I can even get the multiple monitor support to be, considering all of this is just me writing 'hacks' trying to work around the fact that there is no way to detect that some other monitor has focus.

**Comment by koekeishiya** [comment]
Ok so I've improved the focus-code overall and have fixed some issues I were having. It should not get stuck in other situations than what you have mentioned in this issue. Regarding the hammerspoon thing, I can reproduce this with setLevel == floating and menu-fix == disable, but I do not know if this is something that I can fix.

**Comment by chrishoage** [comment]
> Apps like hammerspoon (with the script i wrote)/Honer that draws a border will cause this focus switching to not work properly due to their nature of drawing transparent windows. I will look into integrating this into Kwm itself in the future so that we can allow for this functionality without breaking multi-monitor support. In addition a border could then be drawn around marked windows as well.

Yeah it appears a lot to have to do with the type of "window" itis (above floating type). I have _no_ idea how feasible this actually is but presumably if kwm creates this "window" it might be able to ignore it? Again 0 idea if that is feasible or not. 

> Changing screen focus with mouse will often cause random glitches, will be looked into.

One I have encountered is when the mouse gives focus to another screen the tree appears to "rotate" (not sure if that is actually what is happening just a way to describe it). Using `tree -c refresh` restores the windows into their original position. 

> I can not change the layout of a screen that has no windows.

This really isn't a very big deal (to me at least). What would be nice is the ability to send a window to a empty screen, and have an empty screen "capture" an app. Sounds like you are looking into those issues though.

**Comment by chrishoage** [comment]
> I really do not know how good I can even get the multiple monitor support to be, considering all of this is just me writing 'hacks' trying to work around the fact that there is no way to detect that some other monitor got/has focus.

It's really quite unfortunate OS X does not have better Accessibility APIs surrounding Multiple Monitors. For me having buggy multi monitor support is better than no multi monitor support, especially if the bugs can be worked around with `tree -c refresh`. 

With the knowledge that OSX does not offer such APIs makes me think what you have got so far with your "hacks" is pretty decent.

**Comment by koekeishiya** [comment]
> Looking though the open issues of Amethyst (another WM for OS X) appears to have a lot of issues surrounding Multi monitor support and focus, so doubtful a "perfect" solution is readily available. Users might just have to live with a "good enough" multi monitor support with work workarounds for issues. 

> I personally think it's only worth so much effort if you have to work against the grain.

I get the impression that expect for the mouse-focus bug that happens, and not being able to send a window to an empty screen, the current system is close to as good as it is gonna get. I do use 2external displays in my normal setup, but I am not back home yet and so I have not been able to extensively test how Kwm handles this for daily use.

I guess what I'm trying to say is, that until I personally think the system is good enough, thins will be subject to change.

**Comment by koekeishiya** [comment]
The old code had a lot of redundancy to it, so I rewrote the logic of both the space-transition and monitor-transition code more or less from the ground up.

Hopefully things have improved a lot now and should be consistent.
This should also completely fix the issue where a tree would be re-created (the 'rotate' issue you mentioned).

Again the 'issues' with blank screen is still there for now.

**Comment by chrishoage** [comment]
With this last commit `screen -f next | prev` appears to be broken. The mouse moves to the 2nd display but focus is never actually given to the next display. 

When `screen -f` is given the mouse also moves when `mouse-follows` is disabled. This behavior reminds me I have seen some `mouse-follows` like behavior when not using `window -f next | prev`. One example I can think of is when dragging a floating window from one display to another.

**Comment by koekeishiya** [comment]
Alright so all the issues you mentioned in the above post regarding the 're-write' commit should now be solved.

Notes: 
If a 'monitor-transition' is started by using the command `screen -f ..` or `window -f ..` the mouse will jump to the center of the first leaf window (if one exists and give it focus), or to the center of the screen (if no window exists and perform a left-click) regardless of the state of 'mouse-follows'. This is because of technical limitations.

The above behaviour should no longer happen if a 'screen-transition' occurs by using the mouse. In this case, if the mouse is not above any window on the new screen, it will issue a left-click at that point on the screen to make sure that OSX has now focused the new screen, and windows that are opened, should now "default" to the new screen. If there was a window below the cursor on the new screen, do NOT issue a left-click but rather focus that window.

The reason for the left-click cases is to tell OSX that this is now the focused monitor (stupid 'hack' that I've tried my best to make not interfere with the user, which I think I have succeeded with now).

**Comment by chrishoage** [comment]
> The hammerspoon border script now works when setLevel == normal (menu-fix enabled and disabled) and setLevel == floating (menu-fix disabled).

This is great! `normal` was causing issues with exposé. 

I can confirm that master `HEAD` at the time of writing is working very well. None of the 'monitor-transition' mouse issues bother me because I run with `mouse-follows` on. 

All empty display issues still persist (as you are already aware) so I will leave this issue open.

**Comment by koekeishiya** [comment]
I am so done working with the multi-monitor code now, holy shit what a pain.
Ok so I literally am not gonna bother trying to do the "change layout on a blank monitor" thing.

Capturing and moving windows to a blank screen is once again possible, I hope to god that this did not break any of the previous multi-monitor focus whatever that seemingly was as close to perfect as I am gonna get it.

**Comment by chrishoage** [comment]
I can confirm the empty display issues have been fixed! 

You sir are a steely eyed missile man!
