### ISSUE TITLE
Investigate focused/marked window border with kwm

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#70]
Moving from https://github.com/koekeishiya/kwm/issues/65#issuecomment-170942802 for long term tracking. 

**Issues with Honer/Hammerspoon border drawing:**

 When the window type has a `level` above "normal" it causes issues with kwms ability to focus windows, because these borders are treated as windows/overlays and get mixed in with regular windows.

A native kwm border solution could possibly allow the ability to ignore this special window and have it not interfere with with focusing while being "floating" or higher (thus not interfering with Exposé / mission control. 

**Challenges:**

There is no way to achieve this in raw C / C++. Obj-C / Swift would need to implement it with the Cocca framework and wrap it n a C wrapper to be consumed in kwm. 

By the nature of how borders would be drawn they would be treated as windows. Kwm would need some way to know which window is a border window and ignore it accordingly. 

Floating border windows appear to interfere with focus toggling. This may or may not be fixable with knowing which windows are border windows or the issue my be deeper in the Accessibility API

**Use:** 

Simple configuration should be enough. 
`kwmc config focused-border color 20 64 156 0.8` (r g b a)
`kwmc config focused-border size 5px`
`kwmc config focused-border corners 10px 10px`

A sepereate `kwmc config marked-border` for showing a border around the marked window would be useful as well. If a window is "marked" and "focused" only the marked border would show. (That is up for debate, I can also see value in showing the focused border instead and not the marked.

**Comment by chrishoage** [comment]
I spent some time today to create a CLI file that will take a `NSRect` and a `NSColor` and a width and draw it on the screen 

https://gist.github.com/chrishoage/4336f75d6eba184044d6

Compile
```
swiftc -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk overlay.swift
```

Example usage
```
./overlay  x:2000 y:1800 height:100 width:200 r:1 b:0.2 g:0.5 a:1 line:10
```

This was thrown together over the course of a few hours and I have never worked with a typed/complied language before so apologies for the quality. 

I originally tried to look up the window rect by the window id but I could not figure out how to do that. This very obviously shouldn't be used but maybe it might give you a hint on how you might want to implement this feature. 

It would be cool to just do `./overlay 70467 red:0.3 blue:0.5 green:0.1 alpha: 1` and have the binary figure it out, then kwm could use this binary(?) to pass in the marked or focused window id and manage the process. 

I'm kinda at the end of my knowledge here with with is possible. Ideally the application would not be starting and stopping every time focus changed, I just have no idea if it's possible to call a method in a binary and set the `rect` that way. 

Hopefully this was somewhat helpful

**Comment by chrishoage** [comment]
I got it to work with the `windowId`. It still needs a bit of work (it doesn't account for very think borders and covers the inside of the window too much)

```
./overlay 71824 r:0.3 b:0.4 g:0.8 s:5
./overlay 71824 red:0.3 blue:0.4 green:0.8 stroke:5
```

`w` /  `width`, `h` / `height`, `x`, and `y` override the window position from the `windowId`

**Comment by koekeishiya** [comment]
It is probably more efficient for Kwm to pass the size instead of having the overlay app call CGWindowListCopyWindowInfo, but this approach may work.

So by using this approach, we do not want to "start" the overlay app every time the border needs to be redrawn, but do you know if any of these values can be set through a Swift function call while the overlay is already running?

**Comment by chrishoage** [comment]
> So by using this approach, we do not want to "start" the overlay app every time the border needs to be redrawn, but do you know if any of these values can be set through a Swift function call while the overlay is already running?

Yes the view can be updated while the app is running. I used Honer for a lot of inspiration for how to do this. If the app can receive new values somehow it can use them.  

> The "ideal" way for this approach to work, would be to control the overlay position (and color?) through socket input, so when focus is changed, Kwm can issue a command to update the position, without having to re-create the process.

I agree, I started to investigate the socket idea but it seemed like I needed a library (maybe not I just couldn't figure it out). From my understanding anything Obj-C / C++ / C can do Swift can also do (though bindings](http://chris.eidhof.nl/posts/swift-c-interop.html), so it should be possible. 

 > A problem with making the border be an actual external program tho. If Kwm crashes for some reason, it will not be able to stop the border program. I can specify code to run upon receiving a sigterm signal, but I'm not sure if this will cover all cases.

Yes an external binary I do no think should be the "final" solution. In order to compile this binary people need the Xcode SDK which most people will not have installed. 

What I think should be the "final" solution is importing `kwm` into a `swift` project and initializing and compiling that way. From what I was reading the Obj-C / C++ / C bindings in Swift _should_ allow that to happen. I just am not sure _exactly_ how yet (you might be quicker at figuring it out than me, Even though that swift app is 150 lines it took me hours to write mainly because I was so tripped up by the type system) 

I would also hope that if you launched / imported kwm into a swift project you would be able to better ignore the view? Maybe? No idea there just a hunch.

**Comment by chrishoage** [comment]
> I've made Kwm ignore the hammerspoon border-window for now, as a temporary fix for the loss of focus it would cause. setLevel == floating can now be used regardless of the state of kwmc config menu-fix.

Curious if you could make a case for Honer too? Hammerspoon uses 500mb of RAM. Honer uses 50MB. The only thing I use Hammerspoon for is to draw a border so I'd like to not pay that ram cost for just a border.

**Comment by koekeishiya** [comment]
Fixed in latest commit.

**Comment by chrishoage** [comment]
Yes Honer works very very well. 

I had a probably terrible (as far as efficiency goes) idea: What if we made that overlay.swift app a stand alone companion app that reads the state of `kwmc read marked` and `kwmc read focused` (if focused returned the windowID) every Xms (say 250 or 500 ms) and drew the border accordingly? 

This is still not perfect though, because what Honder does is update the border every time the focus window changes position, which makes the border follow the window almost perfectly. 

In a perfect world kwm could call this "update border" function when it knows the focused window or marked window changed position vs on a polling basis.

**Comment by dominiklohmann** [comment]
What if we could make a `kwmc bind <focus changed> sys <update border>` command?

**Comment by koekeishiya** [comment]
I realized I did not post this, however I was experimenting some with the overlay app you made in Swift.
I did successfully integrate it with Kwm, but because it currently only takes position/size through arguments, I had to re-create it every time focus changed.

If you/we can somehow make the overlay app read from stdin or similar, we should be able to just pipe the updated information to the overlay app by having Kwm use popen() to launch it.

**Comment by chrishoage** [comment]
> If you/we can somehow make the overlay app read from stdin or similar, we should be able to just pipe the updated information to the overlay app by having Kwm use popen() to launch it.

I don't have a ton of time today but I will investigate over the course of this next week. I don't have any typed language / Swift / C experience (aside from that file I wrote) so I will be fumbling around for a bit but I'm sure I can get something working

**Comment by koekeishiya** [comment]
Reading from stdin in Swift

https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_StandardLibrary_Functions/index.html#//apple_ref/swift/func/s:FSs8readLineFT12stripNewlineSb_GSqSS_

**Comment by chrishoage** [comment]
https://gist.github.com/chrishoage/4336f75d6eba184044d6

Ok, updated app to read from stdin. Exact same format as before, expect this time it's not as arguments, but stdin to the shell. 

Please note that this is POC only, if you supply bad arguments the app will crash as I don't do any sanity checking on them. There is no "state" to the app. All state must be passed in each time you issue it a command though stdin 

Build instructions are the same.

**Comment by koekeishiya** [comment]
I've gotten this to work with Kwm using popen as mentioned above, and so far seems to work great.
All that really remains is having Kwm border settings be configured through some Kwmc commands.

Then we need to figurre out how to distribute the Swift Overlay program.

**Comment by chrishoage** [comment]
> Then we need to figure out how to distribute the Swift Overlay program.

I honestly think that this should be distributed with `kvm` as `kwm-overlay` or something. It's not particularly useful outside of `kwm`. Distributing code signed binaries needs to happen anyway.

**Comment by koekeishiya** [comment]
Yeah I've already renamed it to kwm-overlay as well. I'm almost done implementing the border settings. I'll look into getting this up and running when I have time later today.

**Comment by chrishoage** [comment]
I'll clean up the file some more and submit a Pull Request. There is some cleanup I'd like to do to it still.

**Comment by koekeishiya** [comment]
I had to change some settings for it to work across spaces, I'll upload the changed version

**Comment by koekeishiya** [comment]
I pushed a commit where this is in testing.

The application must be called kwm-overlay and placed in the bin directory along with Kwm.

**Comment by koekeishiya** [comment]
I'm thinking of closing this issue and let the kwm-overlay implementation be how this is achieved.
I won't have time to look into objective-c/swift for a long time.

If/when I bother learning Swift, I may just port all of Kwm at that point, instead of having to deal with writing wrappers etc.

**Comment by chrishoage** [comment]
Go ahead and close it. This seems to be working well enough for me. (Better than the honer app and better than the hammerspoon script)

**Comment by koekeishiya** [comment]
So I've been looking into how to write objective-c wrappers, and I've been able to create an NSWindow and draw to screen from within C code. This could potentially allow for borders without the need for managing an external process.

I have no idea yet if this will be done, but I'm experimeting between interoperability of C and Objective-C at the moment.

**Comment by chrishoage** [comment]
That sounds great. In my mind the swift `kwm-overlay` was always a temporary solution. I'd love to see it replaced with something like you describe in the future.
